### ISSUE TITLE
CRT video problems- analog video sync incorrect

### ISSUE THREAD

**Issue by M-Walrus** [MrX-8B/MiSTer-Arcade-RallyX#1]
the image is not aligned correctly using analog out to a CRT television. the image is too far to the right, and has waves in it. Almost half of the map is not visible on the right side of the screen, on my TV. 

It is slightly misaligned vertically as well, with the bottom of the image cutting off where is says "ROUND 1". There is a gap at the top of the screen.

HDMI looks correct. No problem there.

**Comment by MrX-8B** [comment]
This issue will be fixed together when updating the MiSTer framework.
Sorry for the inconvenience, but please wait until then.

**Comment by MrX-8B** [comment]
I did not replace the framework, but I fixed it.
